// <copyright file="ExtensionsTest.Iter.g.cs" company="SuprDewd">Copyright © SuprDewd 2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
//
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
//
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using Microsoft.Pex.Engine.Exceptions;
using Microsoft.Pex.Framework;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace SharpBag
{
    public partial class ExtensionsTest
    {
        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        public void Iter96001()
        {
            IEnumerable<int> iEnumerable;
            int[] ints = new int[0];
            iEnumerable = this.Iter<int>
                              ((IEnumerable<int>)ints, PexChoose.CreateDelegate<Action<int>>());
            Assert.IsNotNull((object)iEnumerable);
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        public void Iter96002()
        {
            IEnumerable<int> iEnumerable;
            int[] ints = new int[0];
            iEnumerable = this.Iter<int>
                              ((IEnumerable<int>)ints, PexChoose.CreateDelegate<Action<int>>());
            Assert.IsNotNull((object)iEnumerable);
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        public void Iter96003()
        {
            IEnumerable<int> iEnumerable;
            int[] ints = new int[0];
            iEnumerable = this.Iter<int>
                              ((IEnumerable<int>)ints, PexChoose.CreateDelegate<Action<int>>());
            Assert.IsNotNull((object)iEnumerable);
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        public void Iter96004()
        {
            IEnumerable<int> iEnumerable;
            int[] ints = new int[0];
            iEnumerable = this.Iter<int>
                              ((IEnumerable<int>)ints, PexChoose.CreateDelegate<Action<int>>());
            Assert.IsNotNull((object)iEnumerable);
        }
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void IterThrowsContractException766()
{
    try
    {
      IEnumerable<int> iEnumerable;
      iEnumerable = this.Iter<int>((IEnumerable<int>)null, (Action<int>)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void IterThrowsContractException919()
{
    try
    {
      IEnumerable<int> iEnumerable;
      int[] ints = new int[0];
      iEnumerable = this.Iter<int>((IEnumerable<int>)ints, (Action<int>)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void Iter960()
{
    IEnumerable<int> iEnumerable;
    int[] ints = new int[0];
    iEnumerable = this.Iter<int>
                      ((IEnumerable<int>)ints, PexChoose.CreateDelegate<Action<int>>());
    Assert.IsNotNull((object)iEnumerable);
}
    }
}