// <copyright file="ExtensionsTest.AsEnumerable03.g.cs" company="SuprDewd">Copyright © SuprDewd 2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
//
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
//
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections;
using System.Collections.Generic;
using Microsoft.Pex.Engine.Exceptions;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace SharpBag
{
    public partial class ExtensionsTest
    {
        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        public void AsEnumerable0314801()
        {
            using (PexDisposableContext disposables = PexDisposableContext.Create())
            {
                IEnumerator<object> iEnumerator;
                IEnumerable<object> iEnumerable;
                object[] os = new object[0];
                iEnumerator = ((IEnumerable<object>)os).GetEnumerator();
                disposables.Add((IDisposable)iEnumerator);
                iEnumerable = this.AsEnumerable03((IEnumerator)iEnumerator);
                disposables.Dispose();
                Assert.IsNotNull((object)iEnumerable);
            }
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        public void AsEnumerable0314802()
        {
            using (PexDisposableContext disposables = PexDisposableContext.Create())
            {
                IEnumerator<object> iEnumerator;
                IEnumerable<object> iEnumerable;
                object[] os = new object[0];
                iEnumerator = ((IEnumerable<object>)os).GetEnumerator();
                disposables.Add((IDisposable)iEnumerator);
                iEnumerable = this.AsEnumerable03((IEnumerator)iEnumerator);
                disposables.Dispose();
                Assert.IsNotNull((object)iEnumerable);
            }
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        public void AsEnumerable0314803()
        {
            using (PexDisposableContext disposables = PexDisposableContext.Create())
            {
                IEnumerator<object> iEnumerator;
                IEnumerable<object> iEnumerable;
                object[] os = new object[0];
                iEnumerator = ((IEnumerable<object>)os).GetEnumerator();
                disposables.Add((IDisposable)iEnumerator);
                iEnumerable = this.AsEnumerable03((IEnumerator)iEnumerator);
                disposables.Dispose();
                Assert.IsNotNull((object)iEnumerable);
            }
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        public void AsEnumerable0314804()
        {
            using (PexDisposableContext disposables = PexDisposableContext.Create())
            {
                IEnumerator<object> iEnumerator;
                IEnumerable<object> iEnumerable;
                object[] os = new object[0];
                iEnumerator = ((IEnumerable<object>)os).GetEnumerator();
                disposables.Add((IDisposable)iEnumerator);
                iEnumerable = this.AsEnumerable03((IEnumerator)iEnumerator);
                disposables.Dispose();
                Assert.IsNotNull((object)iEnumerable);
            }
        }
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void AsEnumerable03148()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      IEnumerator<object> iEnumerator;
      IEnumerable<object> iEnumerable;
      object[] os = new object[0];
      iEnumerator = ((IEnumerable<object>)os).GetEnumerator();
      disposables.Add((IDisposable)iEnumerator);
      iEnumerable = this.AsEnumerable03((IEnumerator)iEnumerator);
      disposables.Dispose();
      Assert.IsNotNull((object)iEnumerable);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void AsEnumerable03ThrowsContractException218()
{
    try
    {
      IEnumerable<object> iEnumerable;
      iEnumerable = this.AsEnumerable03((IEnumerator)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void AsEnumerable0314805()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      IEnumerator<object> iEnumerator;
      IEnumerable<object> iEnumerable;
      object[] os = new object[0];
      iEnumerator = ((IEnumerable<object>)os).GetEnumerator();
      disposables.Add((IDisposable)iEnumerator);
      iEnumerable = this.AsEnumerable03((IEnumerator)iEnumerator);
      disposables.Dispose();
      Assert.IsNotNull((object)iEnumerable);
    }
}
    }
}