// <copyright file="ExtensionsTest.UnionAll01.g.cs" company="SuprDewd">Copyright © SuprDewd 2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
//
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
//
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using Microsoft.Pex.Engine.Exceptions;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace SharpBag
{
    public partial class ExtensionsTest
    {
        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        [PexRaisedContractException(PexExceptionState.Expected)]
        public void UnionAllThrowsContractException888()
        {
            try
            {
                IEnumerable<int> iEnumerable;
                iEnumerable =
                  this.UnionAll<int>((IEnumerable<int>)null, (IEnumerable<int>)null);
                throw
                  new AssertFailedException("expected an exception of type ContractException");
            }
            catch (Exception ex)
            {
                if (!PexContract.IsContractException(ex))
                    throw ex;
            }
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        public void UnionAll0135501()
        {
            IEnumerable<int> iEnumerable;
            int[] ints = new int[0];
            iEnumerable = this.UnionAll01<int>((IEnumerable<int>)ints, 0);
            Assert.IsNotNull((object)iEnumerable);
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        [PexRaisedContractException(PexExceptionState.Expected)]
        public void UnionAll01ThrowsContractException68()
        {
            try
            {
                IEnumerable<int> iEnumerable;
                iEnumerable = this.UnionAll01<int>((IEnumerable<int>)null, 0);
                throw
                  new AssertFailedException("expected an exception of type ContractException");
            }
            catch (Exception ex)
            {
                if (!PexContract.IsContractException(ex))
                    throw ex;
            }
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        public void UnionAll13601()
        {
            IEnumerable<int> iEnumerable;
            int[] ints = new int[0];
            int[] ints1 = new int[0];
            iEnumerable =
              this.UnionAll<int>((IEnumerable<int>)ints, (IEnumerable<int>)ints1);
            Assert.IsNotNull((object)iEnumerable);
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        [PexRaisedContractException(PexExceptionState.Expected)]
        public void UnionAllThrowsContractException498()
        {
            try
            {
                IEnumerable<int> iEnumerable;
                int[] ints = new int[0];
                iEnumerable =
                  this.UnionAll<int>((IEnumerable<int>)ints, (IEnumerable<int>)null);
                throw
                  new AssertFailedException("expected an exception of type ContractException");
            }
            catch (Exception ex)
            {
                if (!PexContract.IsContractException(ex))
                    throw ex;
            }
        }
    }
}