// <copyright file="ExtensionsTest.Execute.g.cs" company="SuprDewd">Copyright © SuprDewd 2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace SharpBag
{
    public partial class ExtensionsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void Execute53301()
{
    int[] ints = new int[0];
    this.Execute<int>((IEnumerable<int>)ints);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void Execute93301()
{
    int[] ints = new int[1];
    this.Execute<int>((IEnumerable<int>)ints);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void Execute424()
{
    int[] ints = new int[2];
    this.Execute<int>((IEnumerable<int>)ints);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ExecuteThrowsContractException889()
{
    try
    {
      this.Execute<int>((IEnumerable<int>)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
