// <copyright file="ExtensionsTest.Shuffle.g.cs" company="SuprDewd">Copyright © SuprDewd 2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
//
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
//
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using Microsoft.Pex.Engine.Exceptions;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace SharpBag
{
    public partial class ExtensionsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void Shuffle521()
{
    IEnumerable<int> iEnumerable;
    int[] ints = new int[0];
    iEnumerable = this.Shuffle<int>((IEnumerable<int>)ints, (Random)null);
    Assert.IsNotNull((object)iEnumerable);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ShuffleThrowsContractException566()
{
    try
    {
      IEnumerable<int> iEnumerable;
      iEnumerable = this.Shuffle<int>((IEnumerable<int>)null, (Random)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void Shuffle875()
{
    IEnumerable<int> iEnumerable;
    int[] ints = new int[1];
    iEnumerable = this.Shuffle<int>((IEnumerable<int>)ints, (Random)null);
    Assert.IsNotNull((object)iEnumerable);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void Shuffle960()
{
    IEnumerable<int> iEnumerable;
    int[] ints = new int[2];
    iEnumerable = this.Shuffle<int>((IEnumerable<int>)ints, (Random)null);
    Assert.IsNotNull((object)iEnumerable);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void Shuffle713()
{
    IEnumerable<int> iEnumerable;
    int[] ints = new int[3];
    iEnumerable = this.Shuffle<int>((IEnumerable<int>)ints, (Random)null);
    Assert.IsNotNull((object)iEnumerable);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void Shuffle632()
{
    IEnumerable<int> iEnumerable;
    int[] ints = new int[4];
    iEnumerable = this.Shuffle<int>((IEnumerable<int>)ints, (Random)null);
    Assert.IsNotNull((object)iEnumerable);
}
    }
}