// <copyright file="ExtensionsTest.IfNotNull01.g.cs" company="SuprDewd">Copyright © SuprDewd 2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
//
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
//
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Engine.Exceptions;
using Microsoft.Pex.Framework;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace SharpBag
{
    public partial class ExtensionsTest
    {
        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        public void IfNotNull0159701()
        {
            this.IfNotNull01<object>((object)null, PexChoose.CreateDelegate<Action>());
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        public void IfNotNull0192301()
        {
            object s0 = new object();
            this.IfNotNull01<object>(s0, PexChoose.CreateDelegate<Action>());
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        public void IfNotNull17301()
        {
            this.IfNotNull<object>((object)null, PexChoose.CreateDelegate<Action<object>>());
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        public void IfNotNull47701()
        {
            object s0 = new object();
            this.IfNotNull<object>(s0, PexChoose.CreateDelegate<Action<object>>());
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        public void IfNotNull0159702()
        {
            this.IfNotNull01<object>((object)null, PexChoose.CreateDelegate<Action>());
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        public void IfNotNull0192302()
        {
            object s0 = new object();
            this.IfNotNull01<object>(s0, PexChoose.CreateDelegate<Action>());
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        public void IfNotNull17302()
        {
            this.IfNotNull<object>((object)null, PexChoose.CreateDelegate<Action<object>>());
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        public void IfNotNull47702()
        {
            object s0 = new object();
            this.IfNotNull<object>(s0, PexChoose.CreateDelegate<Action<object>>());
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        public void IfNotNull0159703()
        {
            this.IfNotNull01<object>((object)null, PexChoose.CreateDelegate<Action>());
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        public void IfNotNull0192303()
        {
            object s0 = new object();
            this.IfNotNull01<object>(s0, PexChoose.CreateDelegate<Action>());
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        public void IfNotNull17303()
        {
            this.IfNotNull<object>((object)null, PexChoose.CreateDelegate<Action<object>>());
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        public void IfNotNull47703()
        {
            object s0 = new object();
            this.IfNotNull<object>(s0, PexChoose.CreateDelegate<Action<object>>());
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        public void IfNotNull0159704()
        {
            this.IfNotNull01<object>((object)null, PexChoose.CreateDelegate<Action>());
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        public void IfNotNull0192304()
        {
            object s0 = new object();
            this.IfNotNull01<object>(s0, PexChoose.CreateDelegate<Action>());
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        public void IfNotNull17304()
        {
            this.IfNotNull<object>((object)null, PexChoose.CreateDelegate<Action<object>>());
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        public void IfNotNull47704()
        {
            object s0 = new object();
            this.IfNotNull<object>(s0, PexChoose.CreateDelegate<Action<object>>());
        }
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void IfNotNull01597()
{
    this.IfNotNull01<object>((object)null, PexChoose.CreateDelegate<Action>());
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void IfNotNull01923()
{
    object s0 = new object();
    this.IfNotNull01<object>(s0, PexChoose.CreateDelegate<Action>());
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void IfNotNull173()
{
    this.IfNotNull<object>((object)null, PexChoose.CreateDelegate<Action<object>>());
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void IfNotNull477()
{
    object s0 = new object();
    this.IfNotNull<object>(s0, PexChoose.CreateDelegate<Action<object>>());
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void If79()
{
    int i;
    i = this.If<int>(0, true, 0);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void If921()
{
    int i;
    i = this.If<int>(0, false, 0);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void IfNotNull01ThrowsContractException708()
{
    try
    {
      this.IfNotNull01<object>((object)null, (Action)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void IfNotNull0159705()
{
    this.IfNotNull01<object>((object)null, PexChoose.CreateDelegate<Action>());
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void IfNotNull0192305()
{
    object s0 = new object();
    this.IfNotNull01<object>(s0, PexChoose.CreateDelegate<Action>());
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void IfNotNullThrowsContractException522()
{
    try
    {
      this.IfNotNull<object>((object)null, (Action<object>)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void IfNotNull17305()
{
    this.IfNotNull<object>((object)null, PexChoose.CreateDelegate<Action<object>>());
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void IfNotNull47705()
{
    object s0 = new object();
    this.IfNotNull<object>(s0, PexChoose.CreateDelegate<Action<object>>());
}
    }
}