// <copyright file="ExtensionsTest.NullOr.g.cs" company="SuprDewd">Copyright © SuprDewd 2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace SharpBag
{
    public partial class ExtensionsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void NullOr90701()
{
    int i;
    i = this.NullOr<object, int>
            ((object)null, PexChoose.CreateDelegate<Func<object, int>>(), 0);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void NullOr71401()
{
    int i;
    object s0 = new object();
    i =
      this.NullOr<object, int>(s0, PexChoose.CreateDelegate<Func<object, int>>(), 0);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void NullOr90702()
{
    int i;
    i = this.NullOr<object, int>
            ((object)null, PexChoose.CreateDelegate<Func<object, int>>(), 0);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void NullOr71402()
{
    int i;
    object s0 = new object();
    i =
      this.NullOr<object, int>(s0, PexChoose.CreateDelegate<Func<object, int>>(), 0);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void NullOr90703()
{
    int i;
    i = this.NullOr<object, int>
            ((object)null, PexChoose.CreateDelegate<Func<object, int>>(), 0);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void NullOr71403()
{
    int i;
    object s0 = new object();
    i =
      this.NullOr<object, int>(s0, PexChoose.CreateDelegate<Func<object, int>>(), 0);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void NullOrThrowsContractException472()
{
    try
    {
      int i;
      i = this.NullOr<object, int>((object)null, (Func<object, int>)null, 0);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void NullOr90704()
{
    int i;
    i = this.NullOr<object, int>
            ((object)null, PexChoose.CreateDelegate<Func<object, int>>(), 0);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void NullOr71404()
{
    int i;
    object s0 = new object();
    i =
      this.NullOr<object, int>(s0, PexChoose.CreateDelegate<Func<object, int>>(), 0);
    Assert.AreEqual<int>(0, i);
}
    }
}
