// <copyright file="ExtensionsTest.EmptyIfNull.g.cs" company="SuprDewd">Copyright © SuprDewd 2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
//
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
//
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System.Collections.Generic;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace SharpBag
{
    public partial class ExtensionsTest
    {
        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        [Ignore]
        [PexDescription("the test state was: duplicate path")]
        public void EmptyIfNull57402()
        {
            IEnumerable<int> iEnumerable;
            iEnumerable = this.EmptyIfNull<int>((IEnumerable<int>)null);
            Assert.IsNotNull((object)iEnumerable);
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        [Ignore]
        [PexDescription("the test state was: duplicate path")]
        public void EmptyIfNull57403()
        {
            IEnumerable<int> iEnumerable;
            iEnumerable = this.EmptyIfNull<int>((IEnumerable<int>)null);
            Assert.IsNotNull((object)iEnumerable);
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        [Ignore]
        [PexDescription("the test state was: duplicate path")]
        public void EmptyIfNull57404()
        {
            IEnumerable<int> iEnumerable;
            iEnumerable = this.EmptyIfNull<int>((IEnumerable<int>)null);
            Assert.IsNotNull((object)iEnumerable);
        }

        [TestMethod]
        [PexGeneratedBy(typeof(ExtensionsTest))]
        [Ignore]
        [PexDescription("the test state was: duplicate path")]
        public void EmptyIfNull57405()
        {
            IEnumerable<int> iEnumerable;
            iEnumerable = this.EmptyIfNull<int>((IEnumerable<int>)null);
            Assert.IsNotNull((object)iEnumerable);
        }
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void EmptyIfNull12201()
{
    IEnumerable<int> iEnumerable;
    int[] ints = new int[0];
    iEnumerable = this.EmptyIfNull<int>((IEnumerable<int>)ints);
    Assert.IsNotNull((object)iEnumerable);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
public void EmptyIfNull57401()
{
    IEnumerable<int> iEnumerable;
    iEnumerable = this.EmptyIfNull<int>((IEnumerable<int>)null);
    Assert.IsNotNull((object)iEnumerable);
}
[TestMethod]
[PexGeneratedBy(typeof(ExtensionsTest))]
[Ignore]
[PexDescription("the test state was: duplicate path")]
public void EmptyIfNull57406()
{
    IEnumerable<int> iEnumerable;
    iEnumerable = this.EmptyIfNull<int>((IEnumerable<int>)null);
    Assert.IsNotNull((object)iEnumerable);
}
    }
}