using Microsoft.Pex.Framework.Generated;
// <copyright file="InternetTest.IsPortFree.g.cs" company="SuprDewd">Copyright © SuprDewd 2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
//
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
//
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace SharpBag.Net
{
    public partial class InternetTest
    {
        [TestMethod]
        [PexGeneratedBy(typeof(InternetTest))]
        public void IsPortFree18()
        {
            bool b;
            b = this.IsPortFree(65537);
            Assert.AreEqual<bool>(false, b);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(InternetTest))]
        public void IsPortFree204()
        {
            bool b;
            b = this.IsPortFree(int.MinValue);
            Assert.AreEqual<bool>(false, b);
        }
    }
}