// <copyright file="MediaExtensionsTest.ToBitmapSource.g.cs" company="SuprDewd">Copyright © SuprDewd 2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Windows.Media.Imaging;
using System.Drawing;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace SharpBag.Media
{
    public partial class MediaExtensionsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(MediaExtensionsTest))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ToBitmapSourceThrowsContractException871()
{
    try
    {
      BitmapSource bitmapSource;
      bitmapSource = this.ToBitmapSource((Image)null);
      throw 
        new AssertFailedException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
    }
}
