// <copyright file="MediaExtensionsTest.Contrast.g.cs" company="SuprDewd">Copyright © SuprDewd 2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace SharpBag.Media
{
    public partial class MediaExtensionsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(MediaExtensionsTest))]
public void Contrast121()
{
    double d;
    d = this.Contrast(6.895854497638472E+115, double.NegativeInfinity);
    Assert.AreEqual<double>(0, d);
}
[TestMethod]
[PexGeneratedBy(typeof(MediaExtensionsTest))]
public void Contrast204()
{
    double d;
    d = this.Contrast(-2.8325168543174093, -0.62688277067687637);
    Assert.AreEqual<double>(1, d);
}
[TestMethod]
[PexGeneratedBy(typeof(MediaExtensionsTest))]
public void Contrast768()
{
    double d;
    d = this.Contrast(0, 0);
    Assert.AreEqual<double>(0.5, d);
}
    }
}
