using Microsoft.Pex.Framework.Generated;

// <copyright file="PascalTriangleTest.GetEntry.g.cs" company="SuprDewd">Copyright © SuprDewd 2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
//
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
//
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace SharpBag.Math
{
    public partial class PascalTriangleTest
    {
        [TestMethod]
        [PexGeneratedBy(typeof(PascalTriangleTest))]
        public void GetEntry793()
        {
            long l;
            l = this.GetEntry(0, 2);
            Assert.AreEqual<long>(0L, l);
        }

        [TestMethod]
        [PexGeneratedBy(typeof(PascalTriangleTest))]
        public void GetEntry195()
        {
            long l;
            l = this.GetEntry(0, 1);
            Assert.AreEqual<long>(0L, l);
        }

        [TestMethod]
        [PexGeneratedBy(typeof(PascalTriangleTest))]
        public void GetEntry399()
        {
            long l;
            l = this.GetEntry(0, 0);
            Assert.AreEqual<long>(1L, l);
        }
    }
}