// <copyright file="PriorityQueueTTest.GetPriorityEnumerator.g.cs" company="SuprDewd">Copyright © SuprDewd 2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
//
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
//
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System.Collections.Generic;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace SharpBag.Algorithms
{
    public partial class PriorityQueueTTest
    {
        [TestMethod]
        [PexGeneratedBy(typeof(PriorityQueueTTest))]
        public void GetPriorityEnumerator72901()
        {
            PriorityQueue<int> priorityQueue;
            IEnumerable<int> iEnumerable;
            priorityQueue = new PriorityQueue<int>();
            iEnumerable = this.GetPriorityEnumerator<int>(priorityQueue);
            Assert.IsNotNull((object)iEnumerable);
            Assert.IsNotNull((object)priorityQueue);
        }
    }
}