// <copyright file="PriorityQueueTTest.Constructor.g.cs" company="SuprDewd">Copyright © SuprDewd 2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace SharpBag.Algorithms
{
    public partial class PriorityQueueTTest
    {
[TestMethod]
[PexGeneratedBy(typeof(PriorityQueueTTest))]
public void Constructor25201()
{
    PriorityQueue<int> priorityQueue;
    priorityQueue = this.Constructor<int>();
    Assert.IsNotNull((object)priorityQueue);
}
    }
}
