// <copyright file="PriorityQueueItemTTest.Constructor.g.cs" company="SuprDewd">Copyright © SuprDewd 2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace SharpBag.Algorithms
{
    public partial class PriorityQueueItemTTest
    {
[TestMethod]
[PexGeneratedBy(typeof(PriorityQueueItemTTest))]
public void Constructor94201()
{
    PriorityQueueItem<int> priorityQueueItem;
    priorityQueueItem = this.Constructor<int>(0, 0);
    Assert.IsNotNull((object)priorityQueueItem);
    Assert.AreEqual<int>(0, priorityQueueItem.Priority);
    Assert.AreEqual<int>(0, priorityQueueItem.Item);
}
    }
}
