using Microsoft.Pex.Framework.Generated;

// <copyright file="PriorityQueueItemTTest.ToString01.g.cs" company="SuprDewd">Copyright © SuprDewd 2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
//
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
//
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace SharpBag.Algorithms
{
    public partial class PriorityQueueItemTTest
    {
        [TestMethod]
        [PexGeneratedBy(typeof(PriorityQueueItemTTest))]
        public void ToString01530()
        {
            string s;
            PriorityQueueItem<int> s0 = new PriorityQueueItem<int>(1, 0);
            s = this.ToString01<int>(s0);
            Assert.AreEqual<string>("1", s);
            Assert.IsNotNull((object)s0);
            Assert.AreEqual<int>(0, s0.Priority);
            Assert.AreEqual<int>(1, s0.Item);
        }

        [TestMethod]
        [PexGeneratedBy(typeof(PriorityQueueItemTTest))]
        public void ToString01827()
        {
            string s;
            PriorityQueueItem<int> s0 = new PriorityQueueItem<int>(0, 0);
            s = this.ToString01<int>(s0);
            Assert.AreEqual<string>("0", s);
            Assert.IsNotNull((object)s0);
            Assert.AreEqual<int>(0, s0.Priority);
            Assert.AreEqual<int>(0, s0.Item);
        }
    }
}