// <copyright file="UtilsTest.CreateIEnumerable.g.cs" company="SuprDewd">Copyright © SuprDewd 2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
//
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
//
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using Microsoft.Pex.Engine.Exceptions;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace SharpBag
{
    public partial class UtilsTest
    {
        [TestMethod]
        [PexGeneratedBy(typeof(UtilsTest))]
        public void CreateIEnumerable420()
        {
            IEnumerable<int> iEnumerable;
            int[] ints = new int[0];
            iEnumerable = this.CreateIEnumerable<int>(ints);
            Assert.IsNotNull((object)iEnumerable);
        }

        [TestMethod]
        [PexGeneratedBy(typeof(UtilsTest))]
        [PexRaisedContractException(PexExceptionState.Expected)]
        public void CreateIEnumerableThrowsContractException485()
        {
            try
            {
                IEnumerable<int> iEnumerable;
                iEnumerable = this.CreateIEnumerable<int>((int[])null);
                throw
                  new AssertFailedException("expected an exception of type ContractException");
            }
            catch (Exception ex)
            {
                if (!PexContract.IsContractException(ex))
                    throw ex;
            }
        }
    }
}