// <copyright file="UtilsTest.ReadLinesFromFile.g.cs" company="SuprDewd">Copyright © SuprDewd 2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
//
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
//
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using Microsoft.Pex.Engine.Exceptions;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace SharpBag
{
    public partial class UtilsTest
    {
        [TestMethod]
        [PexGeneratedBy(typeof(UtilsTest))]
        [PexRaisedContractException(PexExceptionState.Expected)]
        public void ReadLinesFromFileThrowsContractException787()
        {
            try
            {
                IEnumerable<string> iEnumerable;
                iEnumerable = this.ReadLinesFromFile("");
                throw
                  new AssertFailedException("expected an exception of type ContractException");
            }
            catch (Exception ex)
            {
                if (!PexContract.IsContractException(ex))
                    throw ex;
            }
        }

        [TestMethod]
        [PexGeneratedBy(typeof(UtilsTest))]
        [PexRaisedContractException(PexExceptionState.Expected)]
        public void ReadLinesFromFileThrowsContractException244()
        {
            try
            {
                IEnumerable<string> iEnumerable;
                iEnumerable = this.ReadLinesFromFile((string)null);
                throw
                  new AssertFailedException("expected an exception of type ContractException");
            }
            catch (Exception ex)
            {
                if (!PexContract.IsContractException(ex))
                    throw ex;
            }
        }
    }
}